excluded:
    - Pods
    - .build
    - Sports Cards Scanner/Subscription
    - Sports Cards Scanner/Configurations

line_length:
    warning: 200
    error: 280
    ignores_function_declarations: true
    ignores_comments: true
    ignores_interpolated_strings: true
    ignores_urls: true
    
file_length:
    warning: 800
    error: 1500

type_name:
    allowed_symbols: "_"

identifier_name:
    allowed_symbols: "_"
    min_length: 3
    excluded:
        - id
        - up

function_parameter_count:
    warning: 7
    error: 8
    ignores_default_parameters: true

force_cast: error
force_try: error

cyclomatic_complexity:
  ignores_case_statements: true
